### ISSUE TITLE
[TASK] TYPO3 update to 12.4.10 on PHP 8.2 leads to Fatal error

### ISSUE THREAD

**Issue by Bussmeyer** [pixelant/interest#111]
**Describe the bug**
With the TYPO3 update https://get.typo3.org/release-notes/12.4.10 on a PHP 8.2 setup the Symfony Console switched from 6.4 to 7.0
https://github.com/typo3/typo3/commit/b03970d94d

The method signatures of some of the methods changed.
This leads to the following error message in all requests (frontend and backend)

**To Reproduce**

1. Update TYPO3 from 12.4.9 to 12.4.10
2. Open any page
3. See error

Fatal error: Declaration of Pixelant\Interest\Command\UpdateCommandController::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /var/www/html/.build/vendor/pixelant/interest/Classes/Command/UpdateCommandController.php on line 47

**Expected behavior**
All requests should work without errors.

**Desktop (please complete the following information):**
- OS: macOS, ddev
- Browser: all
- Version: all

**Comment by mabolek** [comment]
Hi @Bussmeyer!

Thank you for reporting this.

I guess this should be fixed by specifying Symfony Console as an explicit requirement, and only for v6.4, not allowing v7.

**Comment by Bussmeyer** [comment]
Hi @mabolek, sounds like a solution as well. Would you implement the fix and we close https://github.com/pixelant/interest/pull/112?

**Comment by mabolek** [comment]
Yup, @Bussmeyer. I'll do that.
