### ISSUE TITLE
Add HTTP method GET 

### ISSUE THREAD

**Issue by DavidBruchmann** [pixelant/interest#118]
**Is your feature request related to a problem? Please describe.**
`GET` might be used for many reasons, but one might be to control any desired manipulation only. This is not possible and in my opinion a major flaw of this extension.

**Describe the solution you'd like**
Add the HTTP method `GET`.

**Comment by DavidBruchmann** [comment]
Also checking records before deciding to apply any changes is not possible,

**Comment by mabolek** [comment]
Hi David!

Thank you for the feedback. I'd love to hear more arguments and use cases for this before I consider implementing it. 🙂 

Omitting GET has until now been a very conscious decision. It has three main reasons:

1. The extension is designed to use Remote IDs, so the remote side does not have to know the status of a record within TYPO3. The remote side pushes data *to* TYPO3 and only has to care about whether the operation is a success or not. (You don't have to check if a record exists before pushing, just push.) 
2. Retrieving data would require TYPO3 to have knowledge of what each record's Remote ID would be — including all of its relations. That is impossible, as the only side knowing how to generate a correct Remote ID is the remote side.
3. If data retrieval was possible, how should it be returned? In the way the remote side expects it (that requires knowledge of how the remote side expects the data), as it would be viewed in the backend (i.e. with some formatting), or as it is persisted to the database (which is not how it is received from the remote).

Thus far my answer to these questions has been that it would be better to use other extensions or custom scripts to retrieve the data in the format the remote side expects.


Best wishes

Mathias

**Comment by DavidBruchmann** [comment]
Hi Mathias,

thanks for your response!

I've to admit that my basic requirement is not checking or controlling values in the database, but I've clear requirements to get records either based on table and uid or controller and action.   
Other rest extensions offer those options and allow even to determine the return format beyond json or xml.
As `interest` never has those options and seems farther away than any other solution, probably also in future, the extension is not feasible for the requirements. I thought even about using something like hook, signal/slot or event to implement the desired http method, but probably I've to find several major flaws in each alternative solution till I'd try it again with EXT:interest, I expect it to be unlikely.

Best regards,
David

**Comment by mabolek** [comment]
Hi David!

Maybe this extension could work for you? https://extensions.typo3.org/extension/nnrestapi

The interest extension authenticates and operates as a backend user, so unless that's what you need, it's probably not the solution you need.


— Mathias

**Comment by DavidBruchmann** [comment]
Thanks Mathias,

yes I've chosen that already and hope to get it running soon.

Best Regards,
David
