### ISSUE TITLE
Endpoint cannot be accessed [BUG]

### ISSUE THREAD

**Issue by heaven7** [pixelant/interest#74]
When trying to access the default endpoint `/rest/` there is this error:
`{"success":false,"message":"An exception occurred: PHP Warning: Undefined array key 0 in /www/htdocs/w01ade75/dsw.wmk-dev.de/public/typo3conf/ext/interest/Classes/Router/HttpRequestRouter.php line 63","trace":[]}`

Plugin-Version: 1.0.0-beta-7
Typo3-Version: 11.5.12

Steps to reproduce:
- Composer install interest without any modifications on the extension settings.
- Access default endpoint in frontend.

**Comment by mabolek** [comment]
Hi @heaven7! Thank you for reporting this issue.
