### ISSUE TITLE
Not beeing able to authenticate

### ISSUE THREAD

**Issue by timofo** [pixelant/interest#94]
It is not possible to authenticate me.
$this->request->getHeader('authorization') is always empty because the 'authorization: basic... is not in the request variable.

TYPO3 11 
interest 1.2.0

**Comment by mabolek** [comment]
Hi @timofo! Thank you for submitting the issue. Please describe the steps we can use to replicate the problem.

**Comment by timofo** [comment]
https://docs.typo3.org/p/pixelant/interest/1.2/en-us/Implementing/Rest/Index.html#authentication

When i try this, i always get a 400 Bad Request and the error "No authorization scheme provided."

If i go to the source code and debug it, `$this->request->getHeader('authorization')` is empty always. So the error is because no scheme can be extractet from request.

**Comment by mabolek** [comment]
Please supply a copy of the curl request you're running. I'm interested in the output, so including the `-v` option is important.

Of course, don't forget to remove the base64 string with username and password.

**Comment by timofo** [comment]
`curl -XPOST -H 'Authorization: basic xxxxxxxxxxxxxxxxxxxxxx=' -v 'http://domain.de/rest/authenticate'`

```
> POST /rest/authenticate HTTP/1.1
> Host: domain.de
> User-Agent: curl/8.0.1
> Accept: */*
> Authorization: basic xxxxxxxxxxxxxxxxxxxxxx=
>
< HTTP/1.1 400 Bad Request
< Date: Thu, 06 Jul 2023 07:32:05 GMT
< Server: Apache
< X-TYPO3-Parsetime: 0ms
< Upgrade: h2,h2c
< Connection: Upgrade, close
< X-UA-Compatible: IE=edge
< X-Content-Type-Options: nosniff
< Transfer-Encoding: chunked
< Content-Type: application/json; charset=utf-8
<
{"success":false,"message":"No authorization scheme provided."}* Closing connection 0
```

**Comment by timofo** [comment]
By the way: 
I somehow can't get it to specify a PID for a new page. I didn't mean the remote ID, but when a page should be below another page. New pages are always created below ID 0. 
Could you maybe post some working examples? 

And how do you do it if you want to put e.g. a content on a page where you know the ID (not the remote ID) but the correct ID. Because if you define "pid" in the json the extension always wants to do something with remote ID.
