### ISSUE TITLE
Query result was not an instance of Doctrine\\DBAL\\Driver\\Result

### ISSUE THREAD

**Issue by timofo** [pixelant/interest#95]
interest 1.2.0
TYPO3 10

In TYPO3 11 it works without errors.
In TYPO3 10 i get the following error in tokenrepository.php

{"success":false,"message":"An exception occurred: Query result was not an instance of Doctrine\\DBAL\\Driver\\Result","trace":[]}

my post is: 
`curl -XPOST -H 'Authorization: bearer XXXXXXXXX' 'http://domain.de/rest/pages' -d '{"data":{"remoteID-page-1":{"title":"Neue Seite"}},"metaData":{"storagePid":"39"}}'`

If i debug `$result->fetchOne()` i get the error: {"success":false,"message":"An exception occurred: Call to undefined method Doctrine\\DBAL\\Driver\\Mysqli\\MysqliStatement::fetchOne()","trace":[]}

There is something wrong with backward compatible?

**Comment by timofo** [comment]
It's a "no composer" installation and i think the dbal version is too low.
Is there a way to update this?

because in composer you require 2.11.x and TYPO3 10 in no composer mode has only 2.10.x

**Comment by timofo** [comment]
If not, this extension only work in composer installations.

**Comment by mabolek** [comment]
Indeed, this is a composer-only extension. I can strongly recommend using Composer for your projects. 🙂
