### ISSUE TITLE
empty request_body

### ISSUE THREAD

**Issue by timofo** [pixelant/interest#97]
If i try to delete f.e. a page, i get a success message in response but nothing happened. 
When i look at the log table, i see, that the request_body is empty.
POST and PUT are working. But no DELETE.

Thats the command: `curl -XDELETE -H 'Authorization: bearer sdfadsgdfgdfgdfgdfg' 'https://www.domain.de/rest/pages/remoteID-page-1'`

Response is: `{"success":true,"message":"1 operation completed successfully."}`

Log table says empty request_body.
And i can put as remoteID what i want. Always success and empty request_body.

What could be the issue?

TYPO3 11
interest 1.2.2

**Comment by timofo** [comment]
By the way... composer installation.

**Comment by MattiasNilsson** [comment]
@timofo Do you have some more debug information to provide?

**Comment by mabolek** [comment]
@timofo After a bit of digging, I found the issue and have fixed it in #98

> Delete operations don't need a request body, but the extension was simply quitting early without giving any error message. 
> 
> HTTP DELETE requests with an empty request body will now be executed correctly. All other requests will return a 400 error.

**Comment by MattiasNilsson** [comment]
@timofo A new release is out which fixes the issue: https://github.com/pixelant/interest/releases/tag/1.2.3
